// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt4nEhIcDFO7ThEMf9_6Lgm8ieS94iHX0',
    appId: '1:564183990491:web:1c21d7b50efebb4787ccfe',
    messagingSenderId: '564183990491',
    projectId: 'uni-login-4d0b6',
    authDomain: 'uni-login-4d0b6.firebaseapp.com',
    storageBucket: 'uni-login-4d0b6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb5bNMi4dCI20iY6AI9eQ2tCMRLeVDw0M',
    appId: '1:564183990491:ios:8147e0c0c46ede7087ccfe',
    messagingSenderId: '564183990491',
    projectId: 'uni-login-4d0b6',
    storageBucket: 'uni-login-4d0b6.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt4nEhIcDFO7ThEMf9_6Lgm8ieS94iHX0',
    appId: '1:564183990491:web:77dc3dd07692abb987ccfe',
    messagingSenderId: '564183990491',
    projectId: 'uni-login-4d0b6',
    authDomain: 'uni-login-4d0b6.firebaseapp.com',
    storageBucket: 'uni-login-4d0b6.firebasestorage.app',
  );
}
